name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  # publish-gpr:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         registry-url: https://npm.pkg.github.com/
  #     - run: npm ci
  #     - run: npm run build
  #     - run: npm set //npm.ampire.ch/:_authToken ${{secrets.AMPIRE_TOKEN}}
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm config set registry https://npm.pkg.github.com/
      - run: npm set //npm.pkg.github.com/:_authToken ${{secrets.GITHUB_TOKEN}}
      - run: npm set //npm.ampire.ch/:_authToken ${{secrets.AMPIRE_TOKEN}}
      - run: npm run build
      - run: npm publish